# It is also called a cluster id sometimes.
# If you have different set of servers and you want to have different death message channel for each server,
# you can set the server-group to the server name.
server-group: default

# Redis configuration
redis:
  host: localhost
  port: 6379
  password: ""

# Death Messages
messages:
  PLAYER_KILL:
    default:
      - "&c{player} &e was killed by &a{killer}&r ğŸ˜µ"
    with_weapon:
      - "&c{player} &e was killed by &a{killer} &e using &r{weapon}&r ğŸ”ª"
  ENTITY_ATTACK:
    default:
      - "&c{player} &e was killed by &a{mob}&r ğŸ’€"
  PROJECTILE:
    default:
      - "&c{player} &e was shot to death by a projectile&r ğŸ¹"
  SUFFOCATION:
    default:
      - "&c{player} &e suffocated to death&r ğŸ˜µ"
  FALL:
    default:
      - "&c{player} &e fell to death&r ğŸ•³ï¸"
  FIRE:
    default:
      - "&c{player} &e was burnt to death&r ğŸ”¥"
  FIRE_TICK:
    default:
      - "&c{player} &e was burnt to death&r ğŸ”¥"
  MELTING:
    default:
      - "&c{player} &e melted&r ğŸŒ"
  LAVA:
    default:
      - "&c{player} &e was burnt by lava&r ğŸŒ‹"
  DROWNING:
    default:
      - "&c{player} &e drowned&r ğŸŒŠ"
  BLOCK_EXPLOSION:
    default:
      - "&c{player} &e was blown up by an explosion&r ğŸ’£"
  ENTITY_EXPLOSION:
    default:
      - "&c{player} &e was blown up by an explosion&r ğŸ’£"
  VOID:
    default:
      - "&c{player} &e fell out of the world&r ğŸ•³ï¸"
  LIGHTNING:
    default:
      - "&c{player} &e was struck by lightning&r âš¡"
  SUICIDE:
    default:
      - "&c{player} &e committed suicide&r ğŸ˜”"
  STARVATION:
    default:
      - "&c{player} &e starved to death&r ğŸ½ï¸"
  POISON:
    default:
      - "&c{player} &e was poisoned to death&r â˜ ï¸"
  MAGIC:
    default:
      - "&c{player} &e was killed by magic&r âœ¨"
  WITHER:
    default:
      - "&c{player} &e withered away&r ğŸ’€"
  FALLING_BLOCK:
    default:
      - "&c{player} &e was squashed by a falling block&r ğŸ§±"
  THORNS:
    default:
      - "&c{player} &e was killed by thorns&r ğŸŒµ"
  UNKNOWN:
    default:
      - "&c{player} &e died for unknown reasons&r â“"

